kubefleet-dev/kubefleet

- .github/workflows/upgrade.yml
This PR enables fetching of all history in the upgrade compatibility check.
I have:
N/A
> fix: enable fetching of all history in the upgrade compatibility check

- .github/workflows/upgrade.yml
This PR enables fetching of all history in the upgrade compatibility check.
(The prev. PR misses two test suites)
I have:
N/A
> fix: enable fetching of all history in the upgrade compatibility check (cont'd)

- test/e2e/actuals_test.go
- test/e2e/placement_eviction_test.go
- test/e2e/placement_pickall_test.go
- test/e2e/placement_pickfixed_test.go
- test/e2e/placement_pickn_test.go
- test/e2e/taint_toleration_test.go
- test/e2e/utils_test.go
Increase time waiting for resources removed on the clusters for ITs to reduce flakiness.
Fixes #
I have:
> test: increase time waiting for resource cleanup 

- cmd/hubagent/options/options.go
increase the default resync time to 6 hours
Fixes #
I have:
the resync events can clog the work-queue so we increase the default resync time
> feat: increase the default resync time to 6 hours

- pkg/controllers/clusterresourceplacement/controller.go
- pkg/controllers/clusterresourceplacement/controller_integration_test.go
- pkg/utils/controller/metrics/metrics.go
- test/utils/metrics/metrics.go
Fixes #
I have: Replaced the old placement complete metric with the new placement status metric that has a condition for complete.
v1beta1 ClusterResourcePlacement Integration Test
> feat: update placement status metric

- pkg/controllers/updaterun/controller.go
- pkg/controllers/updaterun/controller_integration_test.go
- pkg/controllers/updaterun/execution.go
- pkg/controllers/updaterun/execution_integration_test.go
- pkg/controllers/updaterun/initialization_integration_test.go
- pkg/controllers/updaterun/validation_integration_test.go
- pkg/utils/condition/condition.go
- pkg/utils/controller/metrics/metrics.go
1. When updateRun is stuck waiting for a cluster update to finish or waiting for after-stage tasks to complete, we mark updateRun Progressing condition to false and add corresponding reacon.
2. Add updateRun status metrics based on updateRun condition. The metric contains 5 labels: name, generation, condition, status and reason. The value is the timestamp when the status metric is emitted.
Generated metrics look like:
```
fleet_workload_update_run_status_last_timestamp_seconds{condition="Succeeded",generation="1",name="example-run",reason="UpdateRunSucceeded",status="True"} 1.7452803474895709e+09
```
Fixes #
I have:
> feat: add metrics for updaterun

- test/e2e/placement_cro_test.go
- test/e2e/placement_ro_test.go
Need to wait for the snapshot appear before creating the CRP otherwise, it's a race between override and rollout controller 
Fixes #
I have:
> fix: fix the override e2e flakiness by waiting for the override snapshot to appear

- pkg/controllers/rollout/controller.go
- pkg/controllers/rollout/controller_integration_test.go
When CRP rollout strategy is changed from `External` to `RollingUpdate`, the rollout is not triggered. This PR fixes this issue.
Fixes #
I have:
> fix: fix rollout controller not rollout when type is changed from External to RollingUpdate

- pkg/controllers/workgenerator/controller.go
- pkg/controllers/workgenerator/controller_integration_test.go
- pkg/controllers/workgenerator/controller_test.go
- pkg/controllers/workgenerator/manifests/resourcequota2.yaml
- pkg/controllers/workgenerator/manifests/test-envelop-configmap.yaml
- pkg/controllers/workgenerator/manifests/test-envelop-configmap2.yaml
- pkg/controllers/workgenerator/suite_test.go
- test/e2e/actuals_test.go
- test/e2e/enveloped_object_placement_test.go
- test/e2e/join_and_leave_test.go
- test/e2e/resources/test-envelop-configmap.yaml
This PR blocks cluster-scoped resources from being wrapped in an envelope to address a security concern.
I have:
> fix: block cluster-scoped resources from being wrapped in an envelope

- apis/placement/v1beta1/clusterresourceplacement_types.go
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml
This PR is the interface update to support showing multiple resourceSnapshot versions across targeted clusters on CRP.
Current behavior:
In current CRP status, there's `crp.status.ObservedResourceIndex` that is always set to the index of the latest resourceSnapshot currently exists on the hub cluster as current rollingUpdate rollout strategy only supports rolling to the latest resourceSnapshot version. The `crp.status.Conditions` (CRP status as a whole) as well as `crp.status.placementStatuses` (each targeted member clsuter status) are both based on this index.
This has several cons:
1. With staged update run enabled, users are able to specify the resourceSnapshot version to rollout. When the version is not the latest, CRP status always shows as "RolloutNotStarted", because …
> interface: support multiple resourceSnapshot versions across clusters

- .github/workflows/ci.yml
- .github/workflows/code-lint.yml
- .github/workflows/trivy.yml
- .github/workflows/upgrade.yml
- .golangci.yml
- docker/hub-agent.Dockerfile
- docker/member-agent.Dockerfile
- docker/refresh-token.Dockerfile
- go.mod
Bump go version to fix CVE
Fixes #
I have:
- [x Run `make reviewable` to ensure this PR is ready for review.
> chore: fix CVE-2025-22871

- cmd/hubagent/main.go
- cmd/memberagent/main.go
Fixes #
I have: setup controller runtime logger to remove trace stack and share logs
Using `DevMode` to make it more human readable.
Example logs:
> feat:  setup controller runtime logger

- test/e2e/actuals_test.go
- test/e2e/drain_tool_test.go
- test/e2e/setup.sh
- test/e2e/setup_test.go
- tools/draincluster/README.md
- tools/draincluster/drain.go
- tools/draincluster/drain_test.go
- tools/draincluster/main.go
- tools/uncordoncluster/README.md
- tools/uncordoncluster/main.go
- tools/uncordoncluster/uncordon.go
- tools/uncordoncluster/uncordon_test.go
> test: Drain tool E2Es, UTs

- pkg/controllers/clusterresourceplacementeviction/controller.go
Example logs:
$ kubectl logs hub-agent-59b749d9bf-gm5dm -n fleet-system | grep "Updated the status of a eviction"
I0501 00:08:19.912290       1 clusterresourceplacementeviction/controller.go:171] "Updated the status of a eviction" clusterResourcePlacementEviction="test-eviction" status={"conditions":[{"type":"Valid","status":"True","observedGeneration":1,"lastTransitionTime":"2025-05-01T00:08:19Z","reason":"ClusterResourcePlacementEvictionValid","message":"Eviction is valid"},{"type":"Executed","status":"True","observedGeneration":1,"lastTransitionTime":"2025-05-01T00:08:19Z","reason":"ClusterResourcePlacementEvictionExecuted","message":"Eviction is allowed, no ClusterResourcePlacementDisruptionBudget specified"}]}
Fixes #
I have:
> util: display eviction status in logs

- apis/placement/v1beta1/stageupdate_types.go
- config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdateruns.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdatestrategies.yaml
- pkg/controllers/updaterun/initialization.go
- pkg/controllers/updaterun/initialization_integration_test.go
- pkg/utils/controller/metrics/metrics.go
1. Make updaterun stage label selector description clearer, differentiate nil and empty selector.
2. List the name of missing selected member clusters in the error message.
Fixes #
I have:
> fix: improve updaterun missing cluster message and label selector API

- pkg/controllers/clusterresourceplacement/resource_selector.go
Recently we have seen some integration test flakiness due to data race, the race stack looks like:
<details>
<summary>Stack Trace</summary>
```
==================
WARNING: DATA RACE
Read at 0x00c00166b620 by goroutine 366:
runtime.mapaccess2_faststr()
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/map_faststr.go:117 +0x0
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedFieldNoCopy()
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/apis/meta/v1/unstructured/helpers.go:61 +0x10f
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedString()
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/apis/meta/v1/unstructured/helpers.go:75 +0x6b
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.getNestedString()
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/apis/meta/v1/ …
```
> fix: fix data race in integration test

- pkg/propertyprovider/azure/suite_test.go
This PR replaces a SKU size for testing in the property provider UTs/ITs as the old SKU size is no longer available in the given region.
I have:
> fix: replace the SKU size for testing in the property provider UTs/ITs

- test/e2e/drain_tool_test.go
Fixes: https://github.com/kubefleet-dev/kubefleet/actions/runs/14786831911/job/41516637200?pr=47
The flakiness occurs because we don't wait for the ClusterResourceBinding to be deleted. TotalPlacements are supposed to be 2 since we already execute a drain
Added logic to ensure no resources exists on drained cluster and also check CRP status
Fixes #
I have:
> test: fix drain E2E flakiness

- go.mod
- go.sum
- pkg/controllers/clusterresourceplacement/resource_selector.go
- pkg/controllers/clusterresourceplacement/resource_selector_test.go
- pkg/controllers/workgenerator/controller.go
- test/e2e/placement_selecting_resources_test.go
- test/integration/cluster_placement_test.go
use helm install order defined https://github.com/helm/helm/blob/31e22b9866af91e1a0ea2ad381798f6c5eec7f4f/pkg/release/util/kind_sorter.go#L31 to sort manifest before creating work objects
Fixes #
I have:
https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/
> feat: use helm apply order to sort selected resources

- pkg/controllers/workapplier/apply.go
- pkg/controllers/workapplier/apply_test.go
- test/e2e/placement_apply_strategy_test.go
This PR fixes an issue in Fleet where apply attempts might fail to due field manager conflicts when SSA (server-side apply) is used; the user will see their first apply op successfully, but any field change later cannot be applied.
Note that this bug exists in both the new and the old work applier; only the new work applier receives the fix.
I have:
A few additional E2E test cases will be sent as separate PRs.
> fix: address a SSA related issue which might cause all apply attempts (except the first one) to fail due to conflicts

- pkg/controllers/updaterun/execution.go
- pkg/controllers/updaterun/execution_test.go
Currently when there're 2 concurrent updateRuns for the same CRP and the same one preempts the first, the first would fail with a very long and hard-to-understand error msg:
```
- lastTransitionTime: "2025-05-13T03:45:41Z"
message: 'cannot continue the ClusterStagedUpdateRun: unexpected behavior which
cannot be handled by the controller: the updating cluster `member1` in the stage
staging does not match the cluster status: &{ClusterName:member1 ResourceOverrideSnapshots:[]
ClusterResourceOverrideSnapshots:[] Conditions:[{Type:Started Status:True ObservedGeneration:1
LastTransitionTime:2025-05-13 03:45:26 +0000 UTC Reason:ClusterUpdatingStarted
Message:Cluster update started}]}, binding: {State:Bound ResourceSnapshotName:example-placement-1-snapshot
ResourceOverrideSnapshots:[] …
```
> fix: fix updateRun error msg when a binding does not have expected state

- .github/copilot-instructions.md
add the copilot instruction to make our agent even more smart
Fixes #
I have:
> docs: add the copilot instruction

- .github/workflows/upgrade.yml
- test/upgrade/setup.sh
- test/upgrade/upgrade.sh
This PR fixes a git time travel issue in the upgrade compatibility tests.
I have:
N/A
N/A
> fix: address a git time travel issue in the upgrade tests

- test/e2e/webhook_test.go
Fixes #
I have:
This particular issue seems to be caused by webhook client's cache miss of the CRP object when CRPDB is created.
https://github.com/kubefleet-dev/kubefleet/actions/runs/15528629716/job/43712797563
https://github.com/kubefleet-dev/kubefleet/actions/runs/15480576534/job/43585554612
Make sure the CRP exists with deletion timestamp before the eviction is created.
https://github.com/kubefleet-dev/kubefleet/actions/runs/15502688865/job/43658951804?pr=90
> fix: fix flaky webhook test

- pkg/controllers/updaterun/controller_integration_test.go
- pkg/controllers/updaterun/initialization.go
- pkg/controllers/updaterun/initialization_integration_test.go
- test/e2e/setup_test.go
- test/e2e/updaterun_test.go
UpdateRun should not report an unscheduled binding with latest policy snapshot as unexpected: this can happen when a member cluster leaves the cluster or a CRP with pickN policy and scaling down. In these cases, the unscheduled bindings should be cleaned up.
Fixes #
I have:
> fix: fix updateRun handling unscheduled bindings

- pkg/controllers/rollout/controller_integration_test.go
Fix the rollout integration tests flakiness caused by the requeue timing.
https://github.com/kubefleet-dev/kubefleet/actions/runs/15696594360/job/44222768634
Fixes #
I have:
See the comments
> test: fix the rollout integration tests flakiness

- cmd/memberagent/main.go
- pkg/controllers/internalmembercluster/v1beta1/member_suite_test.go
- pkg/controllers/workapplier/apply.go
- pkg/controllers/workapplier/controller.go
- pkg/controllers/workapplier/controller_integration_test.go
- pkg/controllers/workapplier/controller_test.go
- pkg/controllers/workapplier/preprocess.go
- pkg/controllers/workapplier/process.go
- pkg/controllers/workapplier/suite_test.go
- test/e2e/enveloped_object_placement_test.go
- test/e2e/placement_apply_strategy_test.go
- test/e2e/placement_pickfixed_test.go
- test/e2e/utils_test.go
Fixes #
I have: 
- now track work that is deleting by using Foreground deletion mode on applied work
- update the owner reference to not block applied work deletion when there is co-ownership.
References: 
- https://github.com/kubernetes/kubernetes/issues/86509#issuecomment-2496053289
- https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
> feat: Change AppliedWork to used foregroundDeletion

- apis/placement/v1alpha1/override_types.go
- apis/placement/v1beta1/override_types.go
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourceoverrides.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourceoverridesnapshots.yaml
- config/crd/bases/placement.kubernetes-fleet.io_resourceoverrides.yaml
- config/crd/bases/placement.kubernetes-fleet.io_resourceoverridesnapshots.yaml
Add scope field in placementRef in override API so that controller can differentiate if the placement referenced is clusterResourcePlacement or resourcePlacement.
API design followed CRD:
https://github.com/kubernetes/kubernetes/blob/032142c53e54e41aff516cf9515c175afeeffd32/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go#L277C1-L283C2
Fixes #
I have:
> interface: add placementScope in override API

- test/e2e/enveloped_object_placement_test.go
This PR fixes a naming error in the envelope related E2E tests.
(the key, `resourceQuota1.yaml`, is never used).
I have:
N/A
Needed for PR #230.
> fix: address a naming error in the envelope related E2E tests

- pkg/controllers/workapplier/controller_integration_test.go
- pkg/controllers/workapplier/controller_test.go
- pkg/controllers/workapplier/drift_detection_takeover.go
- pkg/controllers/workapplier/drift_detection_takeover_test.go
This PR will set the work applier to obscure any drift/diff reportings on the data fields of secret objects, so as to protect sensitive information from being revealed outside cluster boundaries.
This behavior is consistent with what ArgoCD does with similar functions.
I have:
This PR is a re-submission of #238, in an attempt to avoid the unexpected rebasing complications.
> feat: security: obscure drift/diff reportings on secret object data fields (re-submission)

- .github/workflows/ci.yml
This PR sets the E2E GA workflow to use 16-core GitHub large runners, courtesy of CNCF.
I have:
N/A
N/A
> test: enable CNCF large runners for E2E

- Makefile
- docker/hub-agent.Dockerfile
- docker/member-agent.Dockerfile
- docker/refresh-token.Dockerfile
This PR updates the Dockerfiles and Makefile to enable building native ARM64 images on supported platforms. The E2E tests will use the native images if applicable.
I have:
N/A
N/A
> feat: enable ARM64 native support in the upstream repo
