kubefleet-dev/kubefleet

- SECURITY.md
This PR fixes a spelling error in `SECURITY.md`.
I have:
N/A
> fix: a spelling error in SECURITY.md

- hack/Azure/setup/README.md
This PR fixes a failing link in `hack/Azure/setup.md`.
I have:
N/A
> fix: address a failing link in the docs

- .github/workflows/trivy.yml
trivy scan has been cancelled due to https://github.com/actions/runner-images/issues/11101
Fixes #
I have:
> fix: bump the ubuntu version

- .github/workflows/chart.yml
- .github/workflows/trivy.yml
bump helm chart workflow ubuntu version to latest
Fixes #
I have:
> fix: bump helm chart workflow ubuntu version

- pkg/controllers/clusterresourceplacement/controller_integration_test.go
Fixes https://github.com/kubefleet-dev/kubefleet/actions/runs/14540486667/job/40804089257?pr=23
I have: 
- updated tests to ensure all wanted metrics are emitted
- refactored some redudant code
- updated comments
> test: fix flaky metrics test

- .github/workflows/trivy.yml
Fixes https://github.com/kubefleet-dev/kubefleet/actions/runs/14584786006/job/40908280666
I have: bumped to use latest ubuntu version
> fix: bump ubuntu version in trivy pipeline

- test/e2e/placement_selecting_resources_test.go
This PR includes an experimental change; will not be merged to main.
I have:
N/A
N/A
> feat: increase eventually timeout for specific tests [Experimental]

- apis/placement/v1/binding_types.go
- apis/placement/v1/policysnapshot_types.go
- apis/placement/v1/resourcesnapshot_types.go
- apis/placement/v1alpha1/stagedupdate_types.go
- apis/placement/v1beta1/binding_types.go
- apis/placement/v1beta1/policysnapshot_types.go
- apis/placement/v1beta1/resourcesnapshot_types.go
- apis/placement/v1beta1/stageupdate_types.go
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourcesnapshots.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterschedulingpolicysnapshots.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdateruns.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdatestrategies.yaml
Fix shortNames in the API.
Our docs do not use these shortNames except for the updateRuns. I'll fix in the website repo.
Fixes #
I have:
> interface: fix shortnames

- pkg/controllers/workapplier/availability_tracker.go
- pkg/controllers/workapplier/availability_tracker_test.go
> fix: deployment availability check

- pkg/controllers/workapplier/controller.go
fix nil pointer access in applywork controller.go
review comments from PR #51
I have:
tested it in our production environment
> fix: fix nil pointer access in applywork controller.go

- README.md
Add timezone converter to the readme
Fixes #
I have:
> docs: add timezone converter to the readme

- pkg/controllers/clusterresourceplacementeviction/controller_intergration_test.go
- pkg/webhook/add_handler.go
- pkg/webhook/clusterresourceplacementeviction/clusterresourceplacementeviction_validating_webhook.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
- test/e2e/placement_eviction_test.go
- test/e2e/webhook_test.go
> feat: add webhook configuration for cluster resource placement eviction

- pkg/utils/controller/controller.go
- pkg/utils/controller/controller_test.go
Fixes #
I have:
- updated the error wrap functions to ensure APIServer errors are not being categorized as unexpected errors
> fix: update unexpected error and API Server log error types

- .github/copilot-instructions.md
Update copilot instruction to add PR title requirements.
Update copilot instructions.
I have:
No test needed.
None.
> docs: Update copilot-instructions.md

- test/e2e/updaterun_test.go
Add e2e test cases for CRP rollout with rollout strategy transitions: rollingUpdate -> External and External -> rollingUpdate.
Fixes #
I have:
> test: add e2e tests for rollout strategy transitions

- CLAUDE.md
- cmd/hubagent/workload/setup.go
- pkg/controllers/clusterresourceplacement/suite_test.go
- pkg/controllers/clusterresourceplacementwatcher/suite_test.go
- pkg/controllers/clusterresourceplacementwatcher/watcher.go
- pkg/controllers/clusterresourceplacementwatcher/watcher_integration_test.go
refactor clusterresourceplacementwatcher to support rp
Fixes #
I have:
> feat: refactor clusterresourceplacementwatcher to support rp

- cmd/hubagent/workload/setup.go
- pkg/controllers/clusterresourcebindingwatcher/suite_test.go
- pkg/controllers/clusterresourcebindingwatcher/watcher.go
- pkg/controllers/clusterresourcebindingwatcher/watcher_integration_test.go
- pkg/controllers/clusterresourceplacement/suite_test.go
refactor the clusterResourceBinding watcher code
Fixes #
I have:
> feat: support resourceBinding watcher

- cmd/hubagent/workload/setup.go
- pkg/scheduler/watchers/clusterresourceplacement/controller_integration_test.go
- pkg/scheduler/watchers/clusterresourceplacement/suite_test.go
- pkg/scheduler/watchers/clusterresourceplacement/watcher.go
- test/scheduler/suite_test.go
refactor crp scheduler watcher to support RP
Fixes #
I have:
Duplicate the full IT for the RP as there are some dependencies between the tests in order to keep the order and reduce the maintenance cost
> feat: refactor crp watcher for the scheduler

- apis/placement/v1beta1/clusterresourceplacement_types.go
- pkg/controllers/clusterresourceplacement/placement_status.go
- pkg/utils/condition/condition.go
> feat: Add RP condition types and change the internal per cluster condition variable name

- CLAUDE.md
- apis/placement/v1beta1/commons.go
- cmd/hubagent/workload/setup.go
- pkg/controllers/clusterresourceplacement/controller.go
- pkg/controllers/clusterschedulingpolicysnapshot/controller.go
- pkg/controllers/rollout/controller.go
- pkg/controllers/rollout/controller_test.go
- pkg/controllers/rollout/suite_test.go
- pkg/utils/binding/binding.go
- pkg/utils/overrider/overrider.go
- pkg/utils/overrider/overrider_test.go
> feat: refactor rollout controller for RP

- apis/placement/v1beta1/commons.go
- apis/placement/v1beta1/resourcesnapshot_types.go
- cmd/hubagent/workload/setup.go
- pkg/resourcewatcher/change_dector.go
- pkg/utils/apiresources.go
- pkg/utils/apiresources_test.go
Enable resource change detector to start RP controller and add the namespaced resources to skip watch list.
Fixes #
I have:
> feat: enable resource change detector for RP

- apis/placement/v1beta1/clusterresourceplacement_types.go
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourceoverrides.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml
- config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacementstatuses.yaml
- config/crd/bases/placement.kubernetes-fleet.io_resourceplacements.yaml
- test/apis/placement/v1beta1/api_validation_integration_test.go
> feat: add CEL validation for NamespaceAccessible StatusReportingScope

- pkg/controllers/rollout/controller_integration_test.go
- pkg/controllers/rollout/suite_test.go
- pkg/utils/controller/binding_resolver.go
- pkg/utils/controller/binding_resolver_test.go
Add rollout controller IT for RP.
Fixes #
I have:
> test: add rollout controller integration tests for RP

- pkg/controllers/resourcechange/resourcechange_controller.go
- pkg/controllers/resourcechange/resourcechange_controller_test.go
update resource change controller to support ns only for CRP
Fixes #
I have:
added unit tests
> feat: update resource change controller to support ns only for CRP

- apis/cluster/v1beta1/zz_generated.deepcopy.go
- apis/placement/v1alpha1/zz_generated.deepcopy.go
- apis/placement/v1beta1/zz_generated.deepcopy.go
- apis/v1alpha1/zz_generated.deepcopy.go
- go.mod
- test/apis/v1alpha1/zz_generated.deepcopy.go
Bump toolchain version to fix a CVE
Fixes #
I have:
> fix: CVE-2025-47907

- CLAUDE.md
- pkg/controllers/clusterresourceplacement/resource_selector.go
- pkg/controllers/clusterresourceplacement/resource_selector_test.go
- test/utils/informer/manager.go
update the resource_selector to support RP
Fixes #
I have:
added ut
> feat: update the resource_selector to support RP

- cmd/hubagent/options/options.go
- cmd/hubagent/workload/setup.go
- pkg/scheduler/watchers/membercluster/suite_test.go
- pkg/scheduler/watchers/membercluster/watcher.go
- test/scheduler/suite_test.go
Enable resourcePlacement controllers/watchers.
Fixes #
I have:
> feat: enable resourcePlacement controllers

- pkg/controllers/workgenerator/controller.go
- pkg/controllers/workgenerator/controller_integration_test.go
- pkg/controllers/workgenerator/envelope.go
OwnerReferences cannot be added, as the namespaces of work and resourceBinding are different
Fixes #
I have:
> fix: remove the owner reference from work

- cmd/hubagent/workload/setup.go
- pkg/controllers/bindingwatcher/suite_test.go
- pkg/controllers/bindingwatcher/watcher.go
- pkg/controllers/bindingwatcher/watcher_integration_test.go
- pkg/controllers/clusterresourceplacement/suite_test.go
- pkg/controllers/placement/cluster_selector.go
- pkg/controllers/placement/cluster_selector_test.go
- pkg/controllers/placement/controller.go
- pkg/controllers/placement/controller_integration_test.go
- pkg/controllers/placement/controller_test.go
- pkg/controllers/placement/placement_controllerv1alpha1.go
- pkg/controllers/placement/placement_status.go
- pkg/controllers/placement/placement_status_test.go
- pkg/controllers/placement/resource_selector.go
- pkg/controllers/placement/resource_selector_test.go
- pkg/controllers/placement/suite_test.go
- pkg/controllers/placement/work_propagation.go
- pkg/controllers/placementwatcher/suite_test.go
- pkg/controllers/placementwatcher/watcher.go
- pkg/controllers/placementwatcher/watcher_integration_test.go
- pkg/controllers/schedulingpolicysnapshot/controller.go
- pkg/controllers/schedulingpolicysnapshot/controller_integration_test.go
- pkg/controllers/schedulingpolicysnapshot/suite_test.go
Fixes #
I have: removed the cluster in front of the package names
> fix: Update controller package names

- test/e2e/resource_placement_pickall_test.go
- test/e2e/utils_test.go
> test: add rp pickAll tests

- test/e2e/resource_placement_with_custom_config_test.go
> test: add rp tests with custom config

- pkg/propertyprovider/azure/controllers/pod.go
- pkg/propertyprovider/azure/provider.go
This PR sets up some minor improvements in the Azure property provider pod watcher in hope of improving its performance in larger clusters.
I have:
> feat: minor improvement to the pod watcher (azure property provider) for better performance in larger clusters

- pkg/controllers/resourcechange/resourcechange_controller.go
- pkg/controllers/resourcechange/resourcechange_controller_test.go
only trigger the ns scoped resource when the CRP is selecting it in the status or the spec selects the resource.
Fixes #
I have:
> fix: fix the resource change bug

- test/e2e/resource_placement_taint_toleration_test.go
- test/e2e/utils_test.go
> test: add taint and toleration tests for RP

- pkg/controllers/placement/resource_selector.go
- pkg/controllers/placement/resource_selector_test.go
- test/utils/informer/manager.go
- check if the resource is reserved or not
- add more test cases
Fixes #
I have:
> fix: validate if the resource should be placed

- test/e2e/enveloped_object_placement_test.go
- test/e2e/join_and_leave_test.go
- test/e2e/resource_placement_apply_strategy_test.go
- test/e2e/utils_test.go
add RP test for join and leave flow
Fixes #
I have:
> test: add RP test for join and leave flow

- test/e2e/actuals_test.go
- test/e2e/placement_apply_strategy_test.go
- test/e2e/resource_placement_apply_strategy_test.go
- test/e2e/resource_placement_drift_diff_test.go
- test/e2e/resources_test.go
- test/e2e/setup_test.go
- test/e2e/utils_test.go
> test: add RP E2Es for diff/drift

- cmd/hubagent/workload/setup.go
- pkg/controllers/clusterresourceplacementstatuswatcher/suite_test.go
- pkg/controllers/clusterresourceplacementstatuswatcher/watcher.go
- pkg/controllers/clusterresourceplacementstatuswatcher/watcher_integration_test.go
- pkg/controllers/clusterresourceplacementstatuswatcher/watcher_test.go
- test/e2e/placement_status_sync_test.go
Fixes #
I have:
Watcher will be setup in hub agent & E2E will be added once https://github.com/kubefleet-dev/kubefleet/pull/225 is merged
> feat: watcher for CRPS delete events

- pkg/scheduler/framework/framework.go
- pkg/scheduler/framework/framework_test.go
- pkg/scheduler/framework/score.go
- pkg/scheduler/framework/score_test.go
- test/e2e/actuals_test.go
- test/e2e/rollout_test.go
- test/e2e/setup_test.go
- test/e2e/utils_test.go
> chore: Add scheduler and e2e debugging info 

- pkg/controllers/updaterun/validation.go
- pkg/controllers/updaterun/validation_integration_test.go
- pkg/controllers/updaterun/validation_test.go
> feat: Convert Validate function to use interfaces in UpdateRun controller
